orDliveryApp/Areas/Clinet/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using orDatabase;

namespace orDliveryApp.Areas.Clinet.Controllers
{
    public class ItemsController : Controller
    {
        // GET: Clinet/Items
        private OrDeliveryDBEntities db = new OrDeliveryDBEntities();
        public ActionResult Index()
        {
            var sp = _app.UI.CurrentUser.ServiceProvider;
            var cl = db.ItemsCategories.Where(x => x.SPID == sp.SPID);
            var il = db.Items.Where(x => cl.Any(y => x.CatID == y.CatID)).ToList();
            return View(il);
        }

        public ActionResult Create()
        {
            Item p = new Item(true);
             var sp = _app.UI.CurrentUser.ServiceProvider;
            sp.ItemsCategories.Clear();
            sp.ItemsCategories = db.ItemsCategories.Where(x => x.SPID == sp.SPID).ToList();
            if (Request.QueryString["catid"] == null) { ViewBag.CatID = new SelectList(sp.ItemsCategories, "CatID", "CatName"); }
            else { ViewBag.CatID = new SelectList(sp.ItemsCategories, "CatID", "CatName", Convert.ToInt32(Request.QueryString["catid"]) );  }
            

            return View(p);
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("index");
            }
            var sp = _app.UI.CurrentUser.ServiceProvider;
            ViewBag.CatID = new SelectList(sp.ItemsCategories, "CatID", "CatName");
            return View(item);
        }
        public ActionResult Edit(int id)
        {
            var sp = _app.UI.CurrentUser.ServiceProvider;
            var item = db.Items.Find(id);
            sp.ItemsCategories.Clear();
            sp.ItemsCategories = db.ItemsCategories.Where(x => x.SPID == sp.SPID).ToList();
            if (!sp.ItemsCategories.Any(x => x.CatID == item.CatID)) { return HttpNotFound(); }
            ViewBag.CatID = new SelectList(sp.ItemsCategories, "CatID", "CatName",item.CatID);
            return View(item);
        }
        [HttpPost]
        public ActionResult Edit(Item item)
        {
            var old = db.Items.Find(item.ItemID);

            old.Active = item.Active;
            old.ItemName = item.ItemName;
            old.ItemPrice = item.ItemPrice;
            old.CatID = item.CatID;
            old.Photo = _app.UI.Photos.replacePhoto(old.Photo, Request.Files);
            old.Description = item.Description;
            db.Entry(old).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("index");
        }

        public ActionResult Details(int id)
        {
            var item = db.Items.Find(id);
            var sp = _app.UI.CurrentUser.ServiceProvider;
            if (!sp.ItemsCategories.Any(x => x.CatID == item.CatID)) { return HttpNotFound(); }
            return View(item);
        }

    }
}

orDliveryApp/Areas/Clinet/Views/Items/Create.cshtml
@model orDatabase.Item
@{
    ViewBag.Title = "اضافه منتج جديد";
    Layout = "~/Areas/Clinet/Views/Shared/Layouts/_LayoutStructure.cshtml";
    ViewBag.formMode = "create";
    
}



@using (Html.BeginForm((string)ViewBag.Contoler, "Items",
                                        FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.EditorForModel()



    <div class="row col-lg-offset-3">
        <input type="submit" value="حفظ" class="btn btn-darkblue " />
        @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-warning" })


    </div>

}

orDliveryApp/Areas/Clinet/Views/Items/Details.cshtml
@model orDatabase.Item


@{
    ViewBag.Title = Model.ItemName ;
    Layout = "~/Areas/Clinet/Views/Shared/Layouts/_LayoutStructure.cshtml";
    ViewBag.formMode = "details";
}

@Html.EditorForModel();

<div class="row col-lg-offset-3">

    @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-warning" })
    @Html.ActionLink("تعديل", "Edit", new { id = Model.ItemID }, new { @class = "btn btn-success" })
    @Html.ActionLink("خصائص", "index", "ItemProperties", new { id = Model.ItemID }, new { @class = "btn btn-darkblue" })




</div>

orDliveryApp/Areas/Clinet/Views/Items/Edit.cshtml
@model orDatabase.Item
@{
    ViewBag.Title = Model.ItemName ;
    Layout = "~/Areas/Clinet/Views/Shared/Layouts/_LayoutStructure.cshtml";
    ViewBag.formMode = "edit";
}

@using (Html.BeginForm((string)ViewBag.Contoler, "Items",
                                                    FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.EditorForModel()



    <div class="row col-lg-offset-3">
        <input type="submit" value="حفظ" class="btn btn-darkblue " />
        @Html.ActionLink("عوده", "Index", null, new { @class = "btn btn-warning" })


    </div>

}

orDliveryApp/Areas/Clinet/Views/Items/Index.cshtml
@model IEnumerable<orDatabase.Item>
@{
    ViewBag.Title = "المنتجات";
    Layout = "~/Areas/Clinet/Views/Shared/Layouts/_LayoutStructure.cshtml";
}

<p>
    @Html.ActionLink("اضافه", "Create", null, new { @class = "btn btn-black" })
</p>


<table class="table table-striped dataTable">
    <thead>
        <tr>
            <th>

            </th>
            <th>
               الاسم
            </th>
            <th>
                الحاله
            </th>
            <th>
                الطلبات
            </th>
            <th>
                القسم السلعلي
            </th>
            <th>
             السعر
            </th>
            <th>

            </th>
            
            
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="userinfoTbaleImg" src="@_app.UI.Photos.LocalUrl(item.Photo)" alt="">
                </td>
                <td>
                    @Html.ActionLink(item.ItemName, "Details", new { id = item.ItemID })

                </td>
                <td>
                    @if (item.Active)
                    { <span class="info">منتج نشطه</span> }
                    else
                    { <span class="aRed">منتج موقوف</span>}
                </td>
                <td>
                    @item.ItemsCategory.CatName
                </td>
                <td>
                    @item.OrderItems.Count طلب
                </td>
                <td>
                    @item.ItemPrice دينار
                </td>
              
                <th>
                    @Html.ActionLink("الخصائص " + item.Properties.Count, "index","ItemProperties", new { id = item.ItemID }, null)

                </th>

                <td>
                    <div class="row">
                        <div class="col-md-4">
                            <a href="@Url.Action("Details", new { id = item.ItemID })" title="التفاصيل"><i class="fa fa-info"></i></a>
                        </div>

                        <div class="col-md-4">
                            <a href="@Url.Action("Edit", new { id = item.ItemID })" title="تعديل بيانات"><i class="fa fa-pencil"></i></a>
                        </div>

                        @*<div class="col-md-4">
                            <a href="@Url.Action("Delete", new { id = item.ItemID })" class="delete-row danger aRed" title="حذف"><i class="fa fa-trash-o"></i></a>
                        </div>*@

                    </div>



                </td>


            </tr>
        }
    </tbody>
</table>