orDliveryApp/Controllers/API/WebApp/PaymentPortalController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using orDatabase;

namespace orDliveryApp.Controllers.API.WepApp
{
    public class PaymentPortalController : ApiController
    {


        OrDeliveryDBEntities db = new OrDeliveryDBEntities();

        [AllowAnonymous]
        [HttpPost]
        public string Success()
        {

            //var json = new JavaScriptSerializer().Serialize(ob);

            //db = new OrDeliveryDBEntities();
            //var p = db.BankPayements.OrderByDescending(x => x.TransactionDate).Where(x => x.OrderID == 180).FirstOrDefault();

            //Stream req = Request.InputStream;
            //req.Seek(0, System.IO.SeekOrigin.Begin);
            //string json = new StreamReader(req).ReadToEnd();

            //p.UDFs = json ;
            
            //db.SaveChanges();

           return "REDIRECT=https://ordeliverykw.com/PaymentPortal/ok/180";

        }

    }
}

orDliveryApp/Controllers/Web/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using orDatabase;

namespace orDliveryApp.Controllers
{
    public class OrdersController : Controller
    {
        // GET: OrderActions

        private OrDeliveryDBEntities db = new OrDeliveryDBEntities();
        private List<Order> AllOrders()
        {
            return db.Orders.Where(x=> x.OrderStatusID != 1).OrderByDescending(x => x.OrderDate).ToList();
        }

        public ActionResult OrderDetails(int id )
        {
            return View(AllOrders().FirstOrDefault(x=> x.OrderID == id));
        }
        
        public ActionResult FilterByStatus(int id)
        {

           
            if (id == OrderStatusEnum.Competed)
            { ViewBag.completeControl = true; }
            if (id == OrderStatusEnum.DriverDeclined)
            {
                ViewBag.Title = "طلبات سبق رفضها من قبل السائقين";
                return View(AllOrders().Where(x => x.OrderAudits.Any(y => y.NewStatusID == OrderStatusEnum.DriverDeclined)).ToList()); }
            else
            {
                var stat = db.OrderStatues.FirstOrDefault(x => x.StatusID == id);
                ViewBag.Title = stat.StatusName;
                return View(AllOrders().Where(x=> x.OrderStatusID == id).ToList());
            }
            
        }
        public ActionResult index()
        {
            return View(AllOrders());
        }

        public ActionResult CustomerDetails(int id)
        {
            return RedirectToAction("Details", "Customer", new { id = id });
        }
        public ActionResult PickDriver(int id) 
        {
            var ord = db.Orders.FirstOrDefault(x=> x.OrderID == id);
            if (ord.OrderStatusID != orDatabase.OrderStatusEnum.OrderReadyWaiting4Delivery) { return HttpNotFound(); }

            var drv = db.Drivers.Where(x => x.Online == true).ToList();
            
            

            _app.PageClass.PickDriver PD = new _app.PageClass.PickDriver();
            PD.Order = ord;
            foreach (var d in drv)
            {

                _app.PageClass.driverDistance wd = new _app.PageClass.driverDistance();
                _app.PageClass.PickDriverSearchItem jsonSearch = new _app.PageClass.PickDriverSearchItem();
                wd.Driver = d;

                jsonSearch.name = d.User.FullName;
                jsonSearch.driverid = d.DriverID;
                if (d.lastKnownLocation != null)
                {
                    GoogleDistanceMatrix.Services.GoogleDistanceMatrixApi gdapi =
                    new GoogleDistanceMatrix.Services.GoogleDistanceMatrixApi(new[] { d.lastKnownLocation.Lat + "," + d.lastKnownLocation.Lng },
                    new[] { ord.ServiceProvider.Lat + "," + ord.ServiceProvider.Lng });

                    var   r = gdapi.GetResponse();
                    if (r.Rows.Count() > 0)
                    {
                        if (r.Rows[0].Elements[0].Status == "OK")
                        { wd.GoogleRespons = r.Rows[0].Elements[0]; }
                        else { wd.GoogleRespons = null; }
                    }
                    else { wd.GoogleRespons = null; }
                   

                }
                else { wd.GoogleRespons = null; }
                var drvord = d.Orders.ToList();
                var count = drvord.Where(x => OrderStatusEnum.OpenOrders.Any(y => x.OrderStatusID == y)).Count();
                if (count > 0)
                { wd.IsFree = false; jsonSearch.cssClass = "panel-danger"; }
                else { wd.IsFree = true; jsonSearch.cssClass = "panel-success"; }

                //PD.distances.Add(new _app.PageClass.driverDistance { DriverID = d.DriverID , Distance = r });
                PD.Drivers.Add(wd);
                PD.pickDriverSearchItems.Add(jsonSearch);
            }
            var nuldr = PD.Drivers.Where(x => x.GoogleRespons == null).ToList();
            var notnuldv = PD.Drivers.Where(x => x.GoogleRespons != null).ToList();

            PD.Drivers.Clear();
            PD.Drivers.AddRange(notnuldv.OrderBy(x => x.GoogleRespons.Distance.Value));
            PD.Drivers.AddRange(nuldr);

            return View(PD);
        }
        public ActionResult AssignOrder2Driver(int id)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == id);
            dbord.DriverID = Convert.ToInt32(Request.QueryString["did"]) ;
            _app.Audits.NewForStatus7(dbord, _app.UI.CurrentUser.UserID);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }
        //--------- order actions partial view

        public ActionResult DeclineOrder(Order order)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus13(dbord, _app.UI.CurrentUser.UserID, order.DeclineReason);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }
        public ActionResult AcceptOrder(Order order)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus4(dbord, _app.UI.CurrentUser.UserID);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }
        public ActionResult RequestDriver(Order order)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus6(dbord, _app.UI.CurrentUser.UserID);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }
        public ActionResult PackagePickedUp(Order order)
        {

            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus10(dbord, _app.UI.CurrentUser.UserID);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });

        }
        public ActionResult DeliveryFailure(Order order)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus12(dbord, _app.UI.CurrentUser.UserID, order.DeclineReason);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }
        public ActionResult DeliverySuccessful(Order order)
        {
            var dbord = AllOrders().FirstOrDefault(x => x.OrderID == order.OrderID);

            _app.Audits.NewForStatus11(dbord, _app.UI.CurrentUser.UserID);
            db.SaveChanges();
            return RedirectToAction("OrderDetails", new { id = dbord.OrderID });
        }

    }
}

orDliveryApp/Controllers/Web/PaymentPortalController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using orDatabase;


namespace orDliveryApp.Controllers
{
    [AllowAnonymous]
    public class PaymentPortalController : Controller
    {
        // GET: PaymentPortal

        private List<BankPayement> bankPayements() {
            return db.BankPayements.OrderByDescending(x => x.TransactionDate).Where(x=> 
            x.Order.SPID != null).ToList();
        }


        private OrDeliveryDBEntities db = new OrDeliveryDBEntities();
        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ok(int id)
        {
            var p = db.BankPayements.Find(id);
            return View(p);
        }

        [AllowAnonymous]     
        public ActionResult error(int id)
        {
            var p = db.BankPayements.Find(id);
            return View(p);         
        }

        public ActionResult BankError(int id)
        {
            var ord = db.Orders.Find(id);
            var p = ord.BankPayements.ToList().OrderBy(x => x.TransactionDate).LastOrDefault();
            return RedirectToAction("error", p.LocalPayementID );
        }


        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Post)]
        [ActionName("ok")]
        public string ok_post(int id)
        {
           var p = ProcessPayement(id);
            if (p.PaymentStatusID == PayemntStatusEnum.Success) {
                    return "REDIRECT=https://ordeliverykw.com/PaymentPortal/ok/" + p.LocalPayementID.ToString();
            }
            else
            {
                return "REDIRECT=https://ordeliverykw.com/PaymentPortal/error/" + p.LocalPayementID.ToString();

            }
            
        }
        //[AllowAnonymous]
        //[AcceptVerbs(HttpVerbs.Post)]
        //[ActionName("ok")]
        //public ActionResult error_post(int id)
        //{
        //    var p = payement(id, false);
        //    return View(p);

        //}






        private BankPayement ProcessPayement(int id)
        {
            var ord = db.Orders.Find(id);
            Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);
            string queryString = new StreamReader(req).ReadToEnd();

            var dict = HttpUtility.ParseQueryString(queryString);
            var json = new JavaScriptSerializer().Serialize(
                                dict.AllKeys.ToDictionary(k => k, k => dict[k])
                       );
            _app.WepApi.Paymnets.BankResponse model = Newtonsoft.Json.JsonConvert.DeserializeObject<_app.WepApi.Paymnets.BankResponse>(json);


            var p = ord.BankPayements.Where(x => x.BankPayementID == model.PaymentId).FirstOrDefault();
           
            

            if (model.result == "CAPTURED") {
                p.PaymentStatusID = PayemntStatusEnum.Success;
                _app.Audits.NewForStatus2(ord,1, "Auto subment due to successful online payment"); // check out the order
            }
            else { p.PaymentStatusID = PayemntStatusEnum.Failed; }



           


            p.ResultCode = model.result;
            p.AuthCode = model.Auth;
            p.ReferenceID = model.Ref;
            p.TransactionID = model.Tranid;
            p.TrackID = model.trackid;
            p.ResponseBody = json;
            p.UDFs = "eci=" + model.eci;
           




            db.SaveChanges();
            _app.Payments pay = new _app.Payments();
            pay.SendPaymentEmail(p);
            return db.BankPayements.Find(p.LocalPayementID); 

        }
        private string QueryStringData(string name)
        {
            if (Request.QueryString[name] != null) { return Request.QueryString[name]; }
            else return string.Empty;
        }

        public ActionResult index()
        {
            return View(bankPayements());
        }
        public ActionResult PaymentStatus(int id)
        {

            if (id == 1)
            {
                ViewBag.Title = "عمليات مقبوله";
                return View(bankPayements().Where(x => x.PaymentStatusID == PayemntStatusEnum.Success).ToList()); }

            else {
                ViewBag.Title = "عمليات مرفوضه";
                return View(bankPayements().Where(x => x.PaymentStatusID == PayemntStatusEnum.Failed).ToList());
            }
            

        }
        public ActionResult Details(int id)
        {
            var p = db.BankPayements.Find(id);
            return View(p);
        }

    }
}

orDliveryApp/Views/PaymentPortal/Details.cshtml
@model orDatabase.BankPayement
@{
    ViewBag.Title = "عمليه دفع بنكيه";
    Layout = "~/Views/Shared/_Layouts/_LayoutStructure.cshtml";
}

<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("~/Views/Shared/Payments/_PaymentDetails.cshtml", Model)
    </div>

    <div class="panel-footer">
        <div class="col-md-4">

            @if (Model.Order.OrderStatusID != 1)
            {
                @Html.ActionLink("عرض تفاصيل الطلب  " + Model.OrderID.ToString(), "OrderDetails", "Orders", new { id = Model.OrderID }, new { @class = "btn btn-black" })
            }
            else
            {
               <a href="#" class="btn btn-black" disabled>
                   هذا الطلب مازل تحت الانشاء
               </a>
            }

        </div>
        <div class="col-md-4">
            @Html.ActionLink("كل الدفعات البنكيه", "Index", null, new { @class = "btn btn-warning" })
        </div>
       
       
    </div>
    </div>

orDliveryApp/Views/PaymentPortal/GetPaymentID.cshtml
@{
    ViewBag.Title = "GetPaymentID";
    Layout = "~/Views/Shared/_Layouts/_Layout.cshtml";
}

<h2>GetPaymentID</h2>



<div class="col-md-2"></div>
<div class="col-md-8">
    <div class="panel">
        <div class="panel-body text-danger">
            <div class="col-xs-12 text-center">
                <img src="~/Theme/images/Payment/ok.png" style="width:255px; height:255px" alt="ok" />
            </div>
            <div class="col-xs-12 text-center">
                @ViewBag.Url
            </div>
        </div>
    </div>
</div>
<div class="col-md-2"></div>


<script type="text/javascript">
    $('body').addClass('signin');
</script>

orDliveryApp/Views/PaymentPortal/PaymentStatus.cshtml
@model List<orDatabase.BankPayement>
@{
    
    Layout = "~/Views/Shared/_Layouts/_LayoutStructure.cshtml";
}

<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("~/Views/Shared/Payments/_PaymentTable.cshtml", Model)
    </div>

</div>

orDliveryApp/Views/PaymentPortal/index.cshtml
@model List<orDatabase.BankPayement>

@{
    ViewBag.Title = "عمليات الدفع الالكتروني";
    Layout = "~/Views/Shared/_Layouts/_LayoutStructure.cshtml";
}

<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("~/Views/Shared/Payments/_PaymentTable.cshtml", Model)        
    </div>

</div>

orDliveryApp/Views/PaymentPortal/ok.cshtml
@model  orDatabase.BankPayement
@{
    ViewBag.Title = "ok";
    Layout = "~/Views/Shared/_Layouts/_Layout.cshtml";
}



<div class="col-md-2"></div>
<div class="col-md-8">
    <div class="panel">
        <div class="panel-body text-success">
            <div class="col-xs-12 text-center">
                <img src="~/Theme/images/Payment/ok.png" style="width:255px; height:255px" alt="ok" />
            </div>

            <div class="col-xs-12 text-center">
               @Html.Partial("~/Views/Shared/Payments/_PaymentDetails.cshtml", Model)
            </div>

        </div>
    </div>
</div>
<div class="col-md-2"></div>

<script type="text/javascript">
    $('body').addClass('signin'); 
</script>