orDliveryApp/Areas/Clinet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using orDliveryApp;
using orDatabase;

namespace orDliveryApp.Areas.Clinet.Controllers
{
    public class HomeController : Controller
    {
        // GET: Clinet/Home
        public ActionResult Index()
        {
            //ServiceProviderHub spHub = new ServiceProviderHub();


            OrDeliveryDBEntities db = new OrDeliveryDBEntities();
            var sp = _app.UI.CurrentUser.ServiceProvider;

            var ord = sp.Orders;

            _app.PageClass.ClientHomePage hp = new _app.PageClass.ClientHomePage();

            hp.CusAll = ord.Select(x => x.CustomerID).Distinct().Count();

            hp.IsOpen = _app.WepApi.Convert.DB2Json.isWorkinkNow(sp.WrokingFrom, sp.WorkingTill);
            hp.From = sp.WrokingFrom;
            hp.To = sp.WorkingTill;


            hp.OrdAll = ord.Where(x => x.OrderStatusID != 1).Count();         
            hp.OrdOpen = ord.Where(x => OrderStatusEnum.OpenOrders.Any(y => x.OrderStatusID == y && x.OrderStatusID != 1)).Count();
            hp.OrdClosed = hp.OrdAll - hp.OrdOpen;
            hp.OpenOrders = ord.Where(x=> OrderStatusEnum.OpenOrders.Any(y=> x.OrderStatusID == y && x.OrderStatusID != 1));


            foreach (var menu in sp.ItemsCategories.ToList())
            {
                

                foreach (var item in menu.Items.ToList())
                {
                    hp.ItemAll += 1;
                    if (item.Active) { hp.ItemOn += 1; }
                    else { hp.itemOff += 1; }

                }


            }



            var chr = ord.GroupBy(x => x.LastAudit.ActionDate.Date).Select(x => new { value = x.Count(), date = (DateTime)x.Key }).ToList();


            hp.Chart1 = new _app.PageClass.ChartClass
            {
                CanvesID = 1,
                ChartType = "line",
                text = "الطلبات الناجحه في خلال 30 يوم",
                PointTilite = "طلب ",
                label = "عدد الطلبات",
                xAexTitle = "التاريخ" ,
                yAexTitle = "العدد",
                Color = "red",
                Lables = chr.Select(x => x.date.ToShortDateString()).ToArray(),
                Data = chr.Select(x => x.value.ToString()).ToArray()

            };

            return View(hp);
        }



        public ActionResult Search(string keyword)
        {
            _app.PageClass.ClientSearch search = new _app.PageClass.ClientSearch
            {

                KeyWord = keyword


            };
             OrDeliveryDBEntities db = new OrDeliveryDBEntities();
            var sp = db.ServiceProviders.FirstOrDefault(x=> x.SPID == _app.UI.CurrentUser.UserID);
            var ord = sp.Orders.ToList();
            var cus =sp.MyCustomers.ToList();
           

            if (string.IsNullOrEmpty(keyword)) { return View(search); }

            var splstr = keyword.Trim().Split(' ');



            foreach (var s in splstr)
            {

                if (s.Any(x => Char.IsLetter(x)))
                {
                    search.Customers.AddRange(cus.Where(x => x.User.fName.Contains(s) || x.User.lName.Contains(s) ||
                    x.User.mName.Contains(s) || x.User.LoginName.Contains(s) &&
                    !search.Customers.Any(c => x.User.UserID == c.CustomerID)).ToList());


                    foreach (var itemCat in sp.ItemsCategories.ToList())
                    {

                        search.Items.AddRange(itemCat.Items.ToList().Where(x => 
                        x.ItemName.Contains(s)   || Containes(x.Description , s)  ||
                           x.ItemsCategory.CatName.Contains(s) 
                       && !search.Items.Any(y => y.ItemID == x.ItemID)
                        ).ToList());
                    }


                }

                else

                {

                    search.Customers.AddRange(cus.Where(x => x.PhoneNumber.Contains(s) &&
                   !search.Customers.Any(c => x.User.UserID == c.CustomerID)).ToList());


                    foreach (var itemCat in sp.ItemsCategories.ToList())
                    {

                        search.Items.AddRange(itemCat.Items.Where(x => x.ItemPrice.ToString() == s 
                         && !search.Items.Any(y => y.ItemID == x.ItemID)).ToList());
                    }

                    search.Orders.AddRange(ord.Where(x => x.OrderID.ToString().Contains(s)
                   && !search.Orders.Any(y => y.OrderID == x.OrderID)).ToList());


                }


            }

            return View(search);

        }

        private bool Containes(string ob, string value)
        {
            if (string.IsNullOrEmpty(ob)) { return false; }

            return ob.Contains(value);
        }
    }
}

orDliveryApp/Controllers/Web/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using orDatabase;


namespace orDliveryApp.Controllers
{
    public class CustomerController : Controller
    {

        private OrDeliveryDBEntities db = new OrDeliveryDBEntities();



        public ActionResult Index()
        {
           
            return View(db.Customers);
        }


      


        public ActionResult Edit(int id)
        {

            var s = db.Customers.Find(id);
            return View(s);
        }
        [HttpPost]
        public ActionResult Edit(Customer cust)
        {
            var old = db.Customers.Find(cust.CustomerID);


            old.eMail = cust.eMail;
            
            old.User.Active = cust.User.Active;
            old.User.fName = cust.User.fName;
            old.User.mName = cust.User.mName;
            old.User.lName = cust.User.lName;
            old.User.Photo = _app.UI.Photos.replacePhoto(old.User.Photo, cust.User.Photo);
           


            db.Entry(old).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("index");
        }



        public ActionResult Details(int id)
        {
            var s = db.Customers.Find(id);
            return View(s);
        }


        public ActionResult Delete(int id)
        {
            var c = db.Customers.Find(id);
            _app.PageClass.DeleteCustomer cus = new _app.PageClass.DeleteCustomer();
            cus.customer = c;

            if (c.Orders.Count > 0 ) { cus.CanBeDeleted = false; }
            else { cus.CanBeDeleted = true; }

            return View(cus);
        }


        [HttpPost]
        public ActionResult Delete(_app.PageClass.DeleteCustomer cus)
        {
            var c = db.Customers.Find(cus.customer.CustomerID);
            if (c.Orders.Count > 0) { _app.UI.msg.Show = "لا يمكن الحذف"; return View(cus); }



            // c.CustomerAddresses.Clear();
            db.CustomerAddresses.RemoveRange(c.CustomerAddresses);
          
            c.ServiceProviders.Clear();



            // c.User.MobileSessions.Clear();
            db.MobileSessions.RemoveRange(c.User.MobileSessions);

            db.Users.Remove(c.User);
            db.Customers.Remove(c);
            db.SaveChanges();
            return RedirectToAction("index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

orDliveryApp/Controllers/Web/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _app;
using orDatabase;

namespace orDliveryApp.Controllers
{
    public class DriversController : Controller
    {
        // GET: Drivers

        private OrDeliveryDBEntities db = new OrDeliveryDBEntities();


        public ActionResult Index()
        {
            return View( db.Drivers);
        }

        public ActionResult Create()
        {
            Driver d = new Driver { User = new orDatabase.User(true) };

            return View(d);
        }
        [HttpPost]
        public ActionResult Create(Driver d)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    d.User.LoginName = d.PhoneNumber;
                    d.Online = false;
                    db.Drivers.Add(d);
                    db.SaveChanges();
                    return RedirectToAction("index");

                }
            }
            catch (OrException e)
            {
                _app.UI.msg.Show = e.ErrorMessage;
                
            }
           


            return View(d);
        }

        public ActionResult Edit(int id)
        {
            var d = db.Drivers.Find(id);
            return View(d);
        }


        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Edit")]
        public ActionResult Edit(Driver d)
        {


            try
            {
                if (ModelState.IsValid)
                {

                    var old = db.Drivers.Find(d.DriverID);
                    old.BicycleModel = d.BicycleModel;
                    old.LicenseNumber = d.LicenseNumber;
                    old.PhoneNumber = d.PhoneNumber;
                    old.User.Active = d.User.Active;
                    old.User.fName = d.User.fName;
                    old.User.lName = d.User.lName;
                    old.User.LoginName = d.PhoneNumber;
                    old.User.Photo = _app.UI.Photos.replacePhoto(old.User.Photo, d.User.Photo);
                    old.User.mName = d.User.mName;

                    db.Entry(old).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("index");

                }
            }
            catch (OrException e)
            {
                _app.UI.msg.Show = e.ErrorMessage;

            }
           

            return View(d);
        }

        public ActionResult Details(int id)
        {

            var d = db.Drivers.Find(id);
            return View(d);
        }

        public ActionResult Delete(int id)
        {
            var d = db.Drivers.Find(id);
            _app.PageClass.DeleteDriver dp = new _app.PageClass.DeleteDriver();
            dp.Driver = d;
            if (d.Orders.Count > 0) { dp.CanBeDeleted = false; }
            else { dp.CanBeDeleted = true; }
            return View(dp);
        }
        [HttpPost]
        public ActionResult Delete(_app.PageClass.DeleteDriver  dp)
        {
            var d = db.Drivers.Find(dp.Driver.DriverID);

            if (d.Orders.Count == 0)
            {
                db.Drivers.Remove(d);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            return View(dp);
        }


        [HttpPost]
        [MultipleButton(Name = "action", Argument = "RestPassword")]
        public ActionResult RestPassword(Driver drv)
        {
            var d = db.Drivers.FirstOrDefault(x => x.DriverID == drv.DriverID);
            d.User.LoginPassword = "123456789";
            db.SaveChanges();
            _app.UI.msg.Show = ("كلمه المرور الجديده : " + d.User.LoginPassword);
            return RedirectToAction("Edit", new { id = drv.DriverID });
        }
    }
}

orDliveryApp/Controllers/Web/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using orDatabase;

namespace orDliveryApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            if (_app.UI.CurrentUser.ServiceProvider != null) { return RedirectToAction("index", "Home", new { area = "Clinet" }); }

         //   if (_app.UI.CurrentUser.Administrator != null) { return View(); }



            OrDeliveryDBEntities db = new OrDeliveryDBEntities();

            _app.PageClass.AdminHomePage hp = new _app.PageClass.AdminHomePage();

            hp.DrAll = db.Drivers.Count();
            hp.DrOff = db.Drivers.Where(x => x.Online == false).Count();
            hp.DrOn = hp.DrAll - hp.DrOff;

            hp.CusAll = db.Customers.Count();
            hp.CusNew = db.Customers.Where(x => x.CodeDate.HasValue == true).ToList().Where(x => x.CodeDate.Value.AddDays(7) >= _app.DateTime.Now).Count();
            hp.CusOld = hp.CusAll - hp.CusNew;

            hp.OrdAll = db.Orders.Where(x=> x.OrderStatusID != 1).Count();
            hp.OrdOpen = db.Orders.Where(x => OrderStatusEnum.OpenOrders.Any(y => y == x.OrderStatusID) && x.OrderStatusID != 1).Count();
            hp.OrdClosed = hp.OrdAll - hp.OrdOpen;


            hp.AdAll = db.Adds.Count();
            hp.AdOn = db.Adds.Where(x => x.Active == true).Count();
            hp.AdOff = hp.AdAll - hp.AdOn;

            hp.ItemAll = db.Items.Count();
            hp.itemOff = db.Items.Where(x => x.Active == false).Count();
            hp.ItemOn = hp.ItemAll - hp.itemOff;


            hp.OpenOrders = db.Orders.Where(x => OrderStatusEnum.OpenOrders.Any(y => x.OrderStatusID == y && x.OrderStatusID != 1));

            // chart data
            var ordlist = db.Orders.Where(x => x.OrderStatusID == OrderStatusEnum.Competed).ToList().Where(x=>
            x.LastAudit.ActionDate.AddDays(30) >= _app.DateTime.Now).ToList();


            var chr = ordlist.GroupBy(x => x.LastAudit.ActionDate.Date).Select(x => new { value = x.Count(), date = (DateTime)x.Key }).ToList();


            hp.Chart1 = new _app.PageClass.ChartClass
            {
                 CanvesID = 1, ChartType = "line", text="الطلبات الناجحه في خلال 30 يوم", PointTilite = "طلب ",  label = "عدد الطلبات", xAexTitle = "التاريخ"
                , yAexTitle= "العدد", Color = "red",
                //Lables = (from x in ordlist select x.LastAudit.ActionDate.ToShortDateString()).ToArray(),
                Lables = chr.Select(x=> x.date.ToShortDateString()).ToArray(),
                 Data = chr.Select(x=> x.value.ToString()).ToArray()

            };


            var chr1 = ordlist.GroupBy(x => x.ServiceProvider.SpName).Select(x => new { value = x.Count(), spname = x.Key }).ToList();


            hp.Chart2 = new _app.PageClass.ChartClass
            {
                CanvesID = 2, ChartType = "bar", text = "عدد الطلبات علي حسب موفر الخدمه", PointTilite = "طلب", label = "عدد الطلبات", xAexTitle = "مقدمين الخدمات",
                yAexTitle = "عدد الطلبات", Lables = chr1.Select(x => x.spname).ToArray(), Data = chr1.Select(x => x.value.ToString()).ToArray(),
                Color="blue"


            };


            _app.Send.TextMessage text = new _app.Send.TextMessage();
            hp.MessageBlance =  text.GetBalance();

            return View(hp);
        }


        public ActionResult Search( string keyword)
        {
            _app.PageClass.Search search = new _app.PageClass.Search
            {

                KeyWord = keyword


            };
            OrDeliveryDBEntities db = new OrDeliveryDBEntities();

            if (string.IsNullOrEmpty(keyword)) { return View(search); }

            var splstr = keyword.Trim().Split(' ');



            foreach (var s in splstr)
            {

                if (s.Any(x => Char.IsLetter(x)))
                {
                    search.Users.AddRange(db.Users.Where(x => x.fName.Contains(s) || x.lName.Contains(s) ||
                    x.mName.Contains(s) || x.LoginName.Contains(s) && !search.Users.Any(c => x.UserID == c.UserID) && x.Administrator == null).ToList());

                }

                else

                {
                    search.Users.AddRange(db.Users.Where(x => x.Customer.PhoneNumber.Contains(s) || x.Driver.PhoneNumber.Contains(s) 
                    && !search.Users.Any(c => x.UserID == c.UserID)).ToList());

                    search.Orders.AddRange(db.Orders.Where(x => x.OrderID.ToString().Contains(s) && x.OrderStatusID != OrderStatusEnum.NewOrder
                    && !search.Orders.Any(y => y.OrderID == x.OrderID)).ToList());



                }

                
            }

            return View(search);
               
        }


        [AllowAnonymous]
        public ActionResult Wellcome()
        {
            return View();
        }

    }
}

orDliveryApp/Views/Home/Search.cshtml
@model _app.PageClass.Search

@{
    ViewBag.Title = "البحث عن " + Model.KeyWord + " ....";
    Layout = "~/Views/Shared/_Layouts/_LayoutStructure.cshtml";
    string accountType = ""; string PhoneNumber = "000";
}



<script src="~/Theme/js/jquery.highlight-5.js"></script>

@*
        @if (Model.Orders.Count > 0)
    {
    <div class="panel panel-default">
        <div class="panel-body">
        </div>
    </div>
    }
*@



@if (Model.Orders.Count > 0)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>الطلبات</h3>
        </div>
        <div class="panel-body">

            @Html.Partial("~/Views/Shared/Orders/_OrdersTable.cshtml", Model.Orders.ToList())

        </div>
    </div>
}

@if (Model.Users.Count > 0)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>الافراد</h3>
        </div>
        <div class="panel-body">

            <table class="dataTable  col-md-12">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>الاســــم</th>
                        <th>توع الحساب</th>
                        <th>رقم الهاتف</th>
                        <th>حاله الحساب</th>
                        <th>اسم المستخدم</th>

                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.Users)
                    {
                        <tr>
                            <td>
                                @if (item.Driver != null)
                                {
                                    <a href="@Url.Action("Details","Drivers", new { id = item.UserID })">
                                        <img class="userinfoTbaleImg" src="@_app.UI.Photos.LocalUrl(item.Photo)" alt="">
                                    </a>
                                }
                                @if (item.Customer != null)
                                {
                                    <a href="@Url.Action("Details","Customer", new { id = item.UserID })">
                                        <img class="userinfoTbaleImg" src="@_app.UI.Photos.LocalUrl(item.Photo)" alt="">
                                    </a>
                                }
                                @if (item.ServiceProvider != null)
                                {
                                    <a href="@Url.Action("Details","ServiceProviders", new { id = item.UserID })">
                                        <img class="userinfoTbaleImg" src="@_app.UI.Photos.LocalUrl(item.Photo)" alt="">
                                    </a>
                                }


                            </td>
                            <td>

                                @if (item.Driver != null)
                                {
                                    accountType = "سائق"; PhoneNumber = item.Driver.PhoneNumber;

                                    @Html.ActionLink(item.FullName, "Details", "Drivers", new { id = item.UserID }, null)
                                }
                                @if (item.Customer != null)
                                {
                                    accountType = "عميل"; PhoneNumber = item.Customer.PhoneNumber;

                                    @Html.ActionLink(item.FullName, "Details", "Customer", new { id = item.UserID }, null)
                                }
                                @if (item.ServiceProvider != null)
                                {
                                    accountType = "موفر خدمه"; PhoneNumber = "";

                                    @Html.ActionLink(item.FullName, "Details", "ServiceProviders", new { id = item.UserID }, null)
                                }

                            </td>
                            <td>
                                @accountType
                            </td>
                            <td>
                                @PhoneNumber
                            </td>
                            <td>
                                @if (item.Active)
                                {<span class="info">حساب نشط</span> }
                                else
                                { <span class="aRed">حساب موقوف</span>}
                            </td>
                            <td>
                                @item.LoginName
                            </td>

                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>
}


 

<script type="text/javascript">

    $(document).ready(function() {

        var str = '@Model.KeyWord';

        var sa = str.split(' ');

       var arrayLength = sa.length;
        for (var i = 0; i < arrayLength; i++) {
            $('table').highlight(sa[i]);
        }


        $('#keyword').val(str);
      //


    });



</script>